name: Hedera Wallet Snap Code Lint

on: [push, pull_request]

jobs:
  eslint:
    name: Run ESLint For Snap
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out source code

      - uses: actions/setup-node@v2
        name: Set up Node.js
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: packages/hedera-wallet-snap/packages/snap

      - name: Install Dependencies in Subdirectory
        run: yarn install
        working-directory: ./packages/hedera-wallet-snap/packages/snap

      - name: Run ESLint in Subdirectory
        run: yarn lint
        working-directory: ./packages/hedera-wallet-snap/packages/snap
