name: ZXC Publish Snap

on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to checkout:"
        type: string
        required: false
        default: "main"
      snap-package-dir:
        description: "The directory of the snap package to publish:"
        type: string
        required: true
      snap-package-name:
        description: "The name of the snap package to publish:"
        type: string
        required: true
      dry-run-enabled:
        description: "Dry Run Enabled"
        type: string
        default: "false"
    secrets:
      github-token:
        description: "The Github access token used to checkout the repository, submodules, and make GitHub API calls."
        required: true

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write

env:
  NODE_VERSION: 20

jobs:
  package-snap:
    name: Package Snap Directory
    runs-on: smart-contracts-linux-medium
    outputs:
      npm-artifact-name-name: ${{ steps.package-bundle.outputs.package-name }}
    steps:
      - name: Prepare Runner
        uses: pandaswhocode/initialize-github-job@ed4a98646fe0235e6ecf3af5414b355d2abe3bf3 # v1.0.3
        with:
          checkout: 'true'
          checkout-ref: '${{ inputs.ref }}'
          checkout-token: '${{ secrets.github-token }}'
          checkout-fetch-depth: '1'
          setup-node: 'true'
          node-version: '${{ env.NODE_VERSION }}'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Package ${{ inputs.snap-package-name }}
        id: package-bundle
        if: ${{ !cancelled() }}
        env:
          SNAP_DIRECTORY: packages/${{ inputs.snap-package-dir }}/packages/snap
          SNAP_NAME: ${{ inputs.snap-package-name }}
          SNAP_PKG_NAME: ${{ inputs.snap-package-dir }}
          DRY_RUN: ${{ inputs.dry-run-enabled }}
        run: |
          wd=$(pwd)
          cd ${SNAP_DIRECTORY}
          mkdir -p "${wd}/dist"
          PKG_VERSION=$(node -p "require('./package.json').version")
          PKG_NAME="hashgraph-${SNAP_PKG_NAME}-${PKG_VERSION}.tgz"
          yarn install
          yarn run build
          if [[ "${DRY_RUN}" == "true" ]]; then
            yarn pack --dry-run
          else
            echo "${PUBLISH_ARGS}"
            yarn pack --out "${wd}/dist/${PKG_NAME}"
          fi
          
          # Set outputs
          echo "package-name=${PKG_NAME}" >> "${GITHUB_OUTPUT}"
          
          # Summary
          echo "### Published ${SNAP_NAME}" >> "${GITHUB_STEP_SUMMARY}"
          echo "Version is: ${PKG_VERSION}" >> "${GITHUB_STEP_SUMMARY}"
          echo "Dry Run Enabled: ${DRY_RUN}" >> "${GITHUB_STEP_SUMMARY}"
          echo "Package: ${PKG_NAME}" >> "${GITHUB_STEP_SUMMARY}"

      - name: Upload Hedera Custodians Library Package Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: npm-package
          path: ./dist/${{ steps.package-bundle.outputs.package-name }}
          if-no-files-found: error

  publish-snap-packages:
    name: Publish Snap Package
    runs-on: ubuntu-latest
    needs:
      - package-snap
    steps:
      - name: Prepare Runner
        uses: pandaswhocode/initialize-github-job@ed4a98646fe0235e6ecf3af5414b355d2abe3bf3 # v1.0.3
        with:
          checkout: 'true'
          checkout-ref: '${{ inputs.ref }}'
          checkout-fetch-depth: '1'
          checkout-token: '${{ secrets.github-token }}'
          setup-node: 'true'
          node-version: '${{ env.NODE_VERSION }}'
          node-registry: 'https://registry.npmjs.org'

      - name: Install NPM latest
        run: npm install -g npm@11.7.0

      - name: Download Hedera Custodians Library NPM Package
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: npm-package

      - name: Publish NPM Package
        run: |
          args="--access public --no-git-checks"
          if [[ "${{ inputs.dry-run-enabled || 'false' }}" == "true" ]]; then
            args="${args} --dry-run"
          fi

          package="${{ needs.package-snap.outputs.npm-artifact-name }}"
          echo "::group::Publishing package: ${package} with args: ${args}"
          npm publish ${package} ${args}
          echo "::endgroup::"
