name: "ZXC: Test Snap"

on:
  workflow_call:
    inputs:
      snap-package-dir:
        description: "The directory of the snap package to test:"
        type: string
        required: true
      snap-report-name:
        description: "The name of the snap project being tested:"
        type: string
        required: true
      custom-job-label:
        description: "Custom Job Label:"
        type: string
        required: false
        default: "Unit Tests"

defaults:
  run:
    shell: bash

permissions:
  contents: read

env:
  PROJECT_DIRECTORY: packages/${{ inputs.snap-package-dir }}
  SNAP_DIRECTORY: packages/${{ inputs.snap-package-dir }}/packages/snap

jobs:
  unit-test:
    name: ${{ inputs.custom-job-label || 'Unit Tests' }}
    runs-on: smart-contracts-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
          disable-sudo: true

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - name: Setup Yarn
        run: npm install -g corepack && corepack enable

      - name: Yarn Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ env.PROJECT_DIRECTORY }}/.yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.snap-package-dir }}-${{ hashFiles(format('packages/{0}/yarn.lock', inputs.snap-package-dir)) }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.snap-package-dir }}-
            yarn-cache-${{ runner.os }}-${{ inputs.snap-package-dir }}-

      - name: Node Modules Cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ${{ env.PROJECT_DIRECTORY }}/node_modules
            ${{ env.PROJECT_DIRECTORY }}/packages/snap/node_modules
            ${{ env.PROJECT_DIRECTORY }}/packages/site/node_modules
          key: node-modules-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.snap-package-dir }}-${{ hashFiles(format('packages/{0}/yarn.lock', inputs.snap-package-dir)) }}
          restore-keys: |
            node-modules-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.snap-package-dir }}-
            node-modules-cache-${{ runner.os }}-${{ inputs.snap-package-dir }}-

      - name: Install Snap Dependencies
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: yarn install

      - name: Run Snap Unit Tests
        working-directory: ${{ env.SNAP_DIRECTORY }}
        run: yarn test

      - name: Publish Snap Unit Test Reports
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
        with:
          name: ${{ inputs.snap-report-name }} Unit Test Reports
          path: ${{ env.SNAP_DIRECTORY }}/junit*.xml

      - name: Publish Snap Coverage Reports
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
        with:
          name: ${{ inputs.snap-report-name }} Coverage Reports
          path: ${{ env.SNAP_DIRECTORY }}/coverage
